#
#  Author  : Saud Zahir
#  Date    : October 18, 2024
#  Contact : m.saud.zahir@gmail.com
#
#
#  Topic: Compiling Multiple-Source-File Programs
#

all:
	gcc main.c geometry.c

.PHONY: clean

clean:
	rm -rf *.out *.exe
